from __future__ import annotations

from omni_skill_pipeline.models import Audience, GraphEdgeType, GraphNodeType, Modality, ReviewStatus


SKILL_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omni-skill-pipeline.local/schemas/skill.schema.json",
    "title": "SkillDocument",
    "type": "object",
    "additionalProperties": False,
    "required": [
        "skill_id",
        "name",
        "skill_type",
        "goal",
        "audience",
        "trigger",
        "inputs",
        "preconditions",
        "steps",
        "decision_rules",
        "anti_patterns",
        "verification",
        "evidence_refs",
        "confidence",
        "version",
        "summary",
        "tags",
        "source_modality",
        "review_status",
        "created_at",
    ],
    "properties": {
        "skill_id": {"type": "string", "format": "uuid"},
        "name": {"type": "string", "minLength": 1},
        "skill_type": {
            "type": "string",
            "enum": [
                "procedure",
                "decision",
                "diagnostic",
                "analysis",
                "communication",
                "automation",
            ],
        },
        "goal": {"type": "string", "minLength": 1},
        "audience": {"type": "string", "enum": ["self", "junior", "expert"]},
        "trigger": {"type": "array", "items": {"type": "string"}},
        "inputs": {"type": "array", "items": {"type": "string"}},
        "preconditions": {"type": "array", "items": {"type": "string"}},
        "steps": {"type": "array", "items": {"$ref": "#/$defs/skillStep"}},
        "decision_rules": {"type": "array", "items": {"type": "string"}},
        "anti_patterns": {"type": "array", "items": {"type": "string"}},
        "verification": {"type": "array", "items": {"type": "string"}},
        "evidence_refs": {"type": "array", "items": {"type": "string"}},
        "confidence": {"type": "number", "minimum": 0.0, "maximum": 1.0},
        "version": {"type": "string", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"},
        "summary": {"type": "string"},
        "tags": {"type": "array", "items": {"type": "string"}},
        "source_modality": {
            "type": "string",
            "enum": ["text", "audio", "video", "image", "tabular"],
        },
        "review_status": {
            "type": "string",
            "enum": ["draft", "review_pending", "published", "rejected"],
        },
        "created_at": {"type": "string", "format": "date-time"},
    },
    "$defs": {
        "skillStep": {
            "type": "object",
            "additionalProperties": False,
            "required": ["step", "action", "why"],
            "properties": {
                "step": {"type": "integer", "minimum": 1},
                "action": {"type": "string", "minLength": 1},
                "why": {"type": "string"},
            },
        }
    },
}


SKILL_GRAPH_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omni-skill-pipeline.local/schemas/skill-graph.schema.json",
    "title": "SkillGraph",
    "type": "object",
    "additionalProperties": False,
    "required": [
        "name",
        "goal",
        "source_modalities",
        "audience",
        "summary",
        "tags",
        "domain",
        "trigger",
        "inputs",
        "preconditions",
        "steps",
        "decisions",
        "verifications",
        "risks",
        "examples",
        "variables",
        "edges",
        "evidence_refs",
        "atom_refs",
        "confidence",
        "version",
        "review_status",
        "created_at",
        "graph_id",
    ],
    "properties": {
        "name": {"type": "string", "minLength": 1},
        "goal": {"type": "string", "minLength": 1},
        "source_modalities": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string",
                "enum": [item.value for item in Modality],
            },
        },
        "audience": {"type": "string", "enum": [item.value for item in Audience]},
        "summary": {"type": "string"},
        "tags": {"type": "array", "items": {"type": "string"}},
        "domain": {"type": "string", "minLength": 1},
        "trigger": {"type": "array", "items": {"type": "string"}},
        "inputs": {"type": "array", "items": {"type": "string"}},
        "preconditions": {"type": "array", "items": {"type": "string"}},
        "steps": {"type": "array", "items": {"$ref": "#/$defs/stepNode"}},
        "decisions": {"type": "array", "items": {"$ref": "#/$defs/decisionNode"}},
        "verifications": {"type": "array", "items": {"$ref": "#/$defs/verificationNode"}},
        "risks": {"type": "array", "items": {"$ref": "#/$defs/riskNode"}},
        "examples": {"type": "array", "items": {"$ref": "#/$defs/exampleNode"}},
        "variables": {"type": "array", "items": {"$ref": "#/$defs/variableNode"}},
        "edges": {"type": "array", "items": {"$ref": "#/$defs/skillGraphEdge"}},
        "evidence_refs": {"type": "array", "items": {"type": "string"}},
        "atom_refs": {"type": "array", "items": {"type": "string"}},
        "confidence": {"type": "number", "minimum": 0.0, "maximum": 1.0},
        "version": {"type": "string", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"},
        "review_status": {"type": "string", "enum": [item.value for item in ReviewStatus]},
        "created_at": {"type": "string", "format": "date-time"},
        "graph_id": {"type": "string", "minLength": 1},
    },
    "$defs": {
        "stringList": {"type": "array", "items": {"type": "string"}},
        "metadata": {"type": "object"},
        "stepNode": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "step",
                "action",
                "why",
                "atom_refs",
                "evidence_refs",
                "metadata",
                "node_type",
                "node_id",
            ],
            "properties": {
                "step": {"type": "integer", "minimum": 1},
                "action": {"type": "string", "minLength": 1},
                "why": {"type": "string"},
                "atom_refs": {"$ref": "#/$defs/stringList"},
                "evidence_refs": {"$ref": "#/$defs/stringList"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "node_type": {"const": GraphNodeType.STEP.value},
                "node_id": {"type": "string", "minLength": 1},
            },
        },
        "decisionNode": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "condition",
                "decision",
                "rationale",
                "atom_refs",
                "evidence_refs",
                "metadata",
                "node_type",
                "node_id",
            ],
            "properties": {
                "condition": {"type": "string"},
                "decision": {"type": "string"},
                "rationale": {"type": "string"},
                "atom_refs": {"$ref": "#/$defs/stringList"},
                "evidence_refs": {"$ref": "#/$defs/stringList"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "node_type": {"const": GraphNodeType.DECISION.value},
                "node_id": {"type": "string", "minLength": 1},
            },
        },
        "verificationNode": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "check",
                "expected",
                "atom_refs",
                "evidence_refs",
                "metadata",
                "node_type",
                "node_id",
            ],
            "properties": {
                "check": {"type": "string"},
                "expected": {"type": "string"},
                "atom_refs": {"$ref": "#/$defs/stringList"},
                "evidence_refs": {"$ref": "#/$defs/stringList"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "node_type": {"const": GraphNodeType.VERIFICATION.value},
                "node_id": {"type": "string", "minLength": 1},
            },
        },
        "riskNode": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "risk",
                "mitigation",
                "atom_refs",
                "evidence_refs",
                "metadata",
                "node_type",
                "node_id",
            ],
            "properties": {
                "risk": {"type": "string"},
                "mitigation": {"type": "string"},
                "atom_refs": {"$ref": "#/$defs/stringList"},
                "evidence_refs": {"$ref": "#/$defs/stringList"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "node_type": {"const": GraphNodeType.RISK.value},
                "node_id": {"type": "string", "minLength": 1},
            },
        },
        "exampleNode": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "example",
                "classification",
                "atom_refs",
                "evidence_refs",
                "metadata",
                "node_type",
                "node_id",
            ],
            "properties": {
                "example": {"type": "string"},
                "classification": {"type": "string"},
                "atom_refs": {"$ref": "#/$defs/stringList"},
                "evidence_refs": {"$ref": "#/$defs/stringList"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "node_type": {"const": GraphNodeType.EXAMPLE.value},
                "node_id": {"type": "string", "minLength": 1},
            },
        },
        "variableNode": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "name",
                "description",
                "default_value",
                "required",
                "atom_refs",
                "evidence_refs",
                "metadata",
                "node_type",
                "node_id",
            ],
            "properties": {
                "name": {"type": "string"},
                "description": {"type": "string"},
                "default_value": {"type": ["string", "null"]},
                "required": {"type": "boolean"},
                "atom_refs": {"$ref": "#/$defs/stringList"},
                "evidence_refs": {"$ref": "#/$defs/stringList"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "node_type": {"const": GraphNodeType.VARIABLE.value},
                "node_id": {"type": "string", "minLength": 1},
            },
        },
        "skillGraphEdge": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "edge_type",
                "source_node_id",
                "target_node_id",
                "rationale",
                "weight",
                "metadata",
                "edge_id",
            ],
            "properties": {
                "edge_type": {
                    "type": "string",
                    "enum": [item.value for item in GraphEdgeType],
                },
                "source_node_id": {"type": "string", "minLength": 1},
                "target_node_id": {"type": "string", "minLength": 1},
                "rationale": {"type": "string"},
                "weight": {"type": "number"},
                "metadata": {"$ref": "#/$defs/metadata"},
                "edge_id": {"type": "string", "minLength": 1},
            },
        },
    },
}


SCHEMAS = {
    "skill": SKILL_SCHEMA,
    "skill_graph": SKILL_GRAPH_SCHEMA,
}
