apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omni-skill-pipeline
  labels:
    app.kubernetes.io/name: omni-skill-pipeline
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: omni-skill-pipeline.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: omni-skill-pipeline
                port:
                  number: 80
